name: Node.js CI

on:
  push:
    branches: 
      - main 
  pull_request:
    branches:  
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: movie-review-front 
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Determine Cache Directory
      id: npm-cache-dir
      run: echo "dir=node_modules" >> $GITHUB_ENV

    - name: Cache Node Modules
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: ${{ env.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
      env:
        dir: node_modules

    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Set environment variables
      run: |
        echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> $GITHUB_ENV
        
    - name: Build code
      run: npm run build --if-present


    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and tag Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/movie_review-frontend:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/movie_review-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    environment: movie-review-front
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/movie_review-frontend:latest

      - name: Remove previous container
        run: docker rm -f my_mv_frontend

      - name: Run pulled image
        run: |
          docker run -d -p 5173:80 --name my_mv_frontend -e VITE_BASE_URL=${{ secrets.VITE_BASE_URL }} ${{ secrets.DOCKER_USERNAME }}/movie_review-frontend:latest
